version: '3.1'

services:

    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - mongodata:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017

    cardservice:
        container_name: cardservice
        image: cardservice
        links:
            - mongo:mongo

volumes:
    mongodata:


