version: '3.2'

services:

    mongo1:
        hostname: mongo1
        container_name: localmongo1
        image: mongo:4.0-xenial
        networks:
            - starcardsnet
        volumes:
            - mongodata:/data/db
        expose:
            - 27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-replica" ]

    mongo2:
        hostname: mongo2
        container_name: localmongo2
        image: mongo:4.0-xenial
        networks:
            - starcardsnet
        expose:
            - 27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-replica" ]

    mongo3:
        hostname: mongo3
        container_name: localmongo3
        image: mongo:4.0-xenial
        networks:
            - starcardsnet
        expose:
            - 27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-replica" ]

    mongosetup:
        image: mongo
        links: #inutile nel comando docker stack deploy
            - mongo1:mongo1
            - mongo2:mongo2
            - mongo3:mongo3
        volumes:
            - ./Infrastructure/mongo/scripts:/scripts
        networks:
            - starcardsnet
        deploy:
            restart_policy:
                condition: none
        command: /scripts/mongo-replica-setup.sh

    cardservice:
        container_name: cardservice
        image: cardservice
        networks:
            - starcardsnet
        deploy:
            replicas: 2

volumes:
    mongodata:

networks:
    starcardsnet:
        driver: overlay
        attachable: true

