version: '3.2'

services:

    mongo1:
        hostname: mongo1
        container_name: localmongo1
        image: mongo:4.0-xenial
        networks:
            - starcardsnet
        volumes:
            - mongodata:/data/db
        expose:
            - 27017
            - 28017
        ports:
            - 30000:27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-replica" ]

    mongo2:
        hostname: mongo2
        container_name: localmongo2
        image: mongo:4.0-xenial
        networks:
            - starcardsnet
        expose:
            - 27017
            - 28017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-replica" ]

    mongo3:
        hostname: mongo3
        container_name: localmongo3
        image: mongo:4.0-xenial
        networks:
            - starcardsnet
        expose:
            - 27017
            - 28017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-replica" ]

    mongosetup:
        image: mymongo
        container_name: mongosetup
        volumes:
            - ./Infrastructure/mongo/scripts:/scripts
        networks:
            - starcardsnet
        deploy:
            restart_policy:
                condition: on-failure
        command: /scripts/mongo-replica-setup.sh

    rabbitmq:
        image: myrabbitmq
        container_name: rabbitmq
        volumes:
            - rabbitmqdata:/var/lib/rabbitmq
            - ./Infrastructure/rabbitmq/scripts:/scripts
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        command: /scripts/rabbitmq-setup.sh

    cardservice:
        container_name: cardservice
        image: cardservice
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - 5000:80
        networks:
            - starcardsnet
        depends_on:
            - mongo1
        deploy:
            replicas: 2

volumes:
    mongodata:
    rabbitmqdata:

networks:
    starcardsnet:
        driver: overlay
        attachable: true

