FROM loicsharma/baget

EXPOSE 80


#ENV ApiKey NUGET-SERVER-API-KEY
#ENV Storage__Type FileSystem
#ENV Storage__Path /var/baget/packages
#ENV Database__Type Sqlite
#ENV Database__ConnectionString Data Source=/var/baget/baget.db
#ENV Search__Type Database

#VOLUME ./baget-data /var/baget

#docker run --rm --name nuget-server -p 5555:80 --env-file baget.env -v "$(pwd)/baget-data:/var/baget" loicsharma/baget:latest


